### ISSUE TITLE
Python syntax error

### ISSUE THREAD

**Issue by LiangJYu** [opera-adt/PROTEUS#22]
https://github.com/opera-adt/PROTEUS/blob/08fd57c64fec6f9d2e02da7e84aca86982f9bccd/src/proteus/core.py#L49

Should be `os.remove()`.

Was discovered [here](https://github.com/opera-adt/COMPASS/pull/28#discussion_r880899577)

**Comment by gshiroma** [comment]
Thank you for finding this, @LiangJYu ! This issue is being addressed in PR #21 commit: https://github.com/opera-adt/PROTEUS/pull/21/commits/51d25005bb32351e723bebd529b85f65dd7e1095
